// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeYQCzFZ0G8cxI0ldMrStG9paJmU165kk',
    appId: '1:487583856520:android:cd1267666ab65cb1d3ec3d',
    messagingSenderId: '487583856520',
    projectId: 'flutter-instagram-burger',
    storageBucket: 'flutter-instagram-burger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9TQWkHmbt-ISsNrjzDcTnO7FErQUmQI',
    appId: '1:487583856520:ios:9aabeabe46f0419cd3ec3d',
    messagingSenderId: '487583856520',
    projectId: 'flutter-instagram-burger',
    storageBucket: 'flutter-instagram-burger.appspot.com',
    androidClientId: '487583856520-hrdob8nej84427g7eu07oqeulqi2bpqb.apps.googleusercontent.com',
    iosClientId: '487583856520-7n6emjhl8873rakoo9h2sge86es85mq7.apps.googleusercontent.com',
    iosBundleId: 'com.blac2013.flutterInstagramClone',
  );
}
